import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Jost } from "next/font/google";

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost", // creates a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const boot = `
//     try {
//       const raw = localStorage.getItem("app-theme");
//       if (raw) {
//         const t = JSON.parse(raw);
//         const el = document.documentElement;
//         function apply(prefix, scale) {
//           for (const k in scale) {
//             el.style.setProperty("--color-" + prefix + "-" + k, scale[k]);
//           }
//         }
//         if (t.primary) apply("primary", t.primary);
//         if (t.secondary) apply("secondary", t.secondary);
//       }
//     } catch {}
//   `;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script />
      </head>
      <body className={`${jost.variable} antialiased`}>{children}</body>
    </html>
  );
}
